### ISSUE TITLE
addItemEnclosure()

### ISSUE THREAD

**Issue by sjaakp** [zelenin/RSS-Generator#1]
Hi Zelenin,

addItemEnclosure() does not work as expected, because the $url parameter is normalized in addItemElement().

Regards,
Sjaak

**Comment by zelenin** [comment]
I see that generator generate this:
```
<enclosure url="http://example.com/mp3.mp3" length="99999" type="audio/mpeg"/>
```
?

**Comment by sjaakp** [comment]
Sorry, you’re right, my mistake.

 

Sjaak

 

Van: Aleksandr Zelenin [mailto:notifications@github.com] 
Verzonden: zondag 13 september 2015 13:09
Aan: zelenin/RSS-Generator
CC: Sjaak Priester
Onderwerp: Re: [RSS-Generator] addItemEnclosure() (#1)

 

I see that generator generate this:

<enclosure url=" <http://example.com/mp3.mp3> http://example.com/mp3.mp3" length="99999" type="audio/mpeg"/>

?
